### ISSUE TITLE
implimentation

### ISSUE THREAD

**Issue by GG82** [nealjack/BMO#1]
Hi, Great work on the BMO model though its missing the arm and leg files.

Could you give me an idea as to how this would be run from a pi OS (Raspbian). I assume you would need an upstart script. 

Thanks

**Comment by nealjack** [comment]
Hi,

Let me start out by saying this is very much a work in progress. I've been too busy recently to continue work on this project, although I very much mean to.

The arms and legs are made from fabric and bendy foam tubes, not 3D printed plastic, so there are no files for them.

The current iteration of BMO is built to use the C.H.I.P and only require USB (for the HID controls), but expects a built in charging controller for the battery, which the Raspberry Pi lacks. I imagine Sparkfun or Adafruit make charging controllers that could be used with the RPI. As for setup scripts, there aren't any yet, but I've been playing around with using emulation station and similar projects.
